spring:
  application:
    name: Grabfood API
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url: jdbc:mysql://localhost:3306/grab-food
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
server:
  port: 6969
  servlet:
    context-path: /grab
logging:
  level:
    org.springframework.security: DEBUG
